### ISSUE TITLE
stan model fails on test case

### ISSUE THREAD

**Issue by sdwfrost** [nicholasjclark/mvgam#5]
The following code, taken from the documentation, results in an error when run using Stan:

```r
library(dplyr)
library(mvgam)
trend <- cumsum(rnorm(53, -0.1, 0.5))
observations <- rnbinom(53, size = 10, mu = 4 + exp(trend))
data.frame(y = observations) %>%
  dplyr::mutate(lag1 = lag(y),
                lag2 = lag(y, 2),
                lag3 = lag(y, 3)) %>%
  dplyr::slice_tail(n = 50) -> sim_dat
sim_dat$time <- 1:50
data_train <- sim_dat[1:40,]
data_test <- sim_dat[41:50,]
m_mvgam <- mvgam(formula = y ~ 1,
                 data = data_train,
                 newdata = data_test,
                 family = 'nb',
                 trend_model = 'AR3',
                 chains = 4,
                 burnin = 1000,
                 use_stan = TRUE)
```

```r
Warning: gam.fit3 algorithm did not convergeUsing rstan as the backend

Compiling the Stan program...

SYNTAX ERROR, MESSAGE(S) FROM PARSER:
Variable "vector" does not exist.
 error in 'model5bd849a9767d_d92ad29b307e0dec0b2df017db20274c' at line 89, column 6
  -------------------------------------------------
    87: 
    88: // likelihood functions
    89: vector[n_nonmissing] flat_trends;
             ^
    90: real flat_rs[n_nonmissing];
  -------------------------------------------------

Error in stanc(file = file, model_code = model_code, model_name = model_name,  : 
  failed to parse Stan model 'd92ad29b307e0dec0b2df017db20274c' due to the above error.
```

**Comment by nicholasjclark** [comment]
Thanks for letting me know Simon. Unfortunatley that is an error due to older Stan versions requiring all variables be declared at the top of their respective blocks. This has been relaxed in recent versions, which is why my tests weren't picking that up. I will introduce a patch to fix this issue, but I'd strongly recommend you use Cmdstan for all your Stan models. Performance is much better and models are easier to write / debug. Will let you know when it is ready

**Comment by nicholasjclark** [comment]
Ok, I've made a few slight changes and hopefully I've caught all the places where variables were not declared at the top of blocks. My tests using rstan version 2.26.13 (Stan version 2.26.1) have all passed. Would you mind removing and reinstalling mvgam to see if your models can fit?

**Comment by sdwfrost** [comment]
Thanks! Using the latest Stan (not the one on CRAN), it all seems to work now. Before I updated to the latest Stan, the `array` declaration was causing a problem.
