### ISSUE TITLE
Applying discrete effects

### ISSUE THREAD

**Issue by roaldarbol** [nicholasjclark/mvgam#57]
Hi Nicholas!

Just starting my adventures into these types of models, so I hope it's alright to post a question here (the Discussion isn't open, so can't ask there). Otherwise, just point me somewhere else. :-)

I'm wondering if it is possible to add effects of factors in a meaningful way? E.g. if I'm activity of glowworms, and I have periods of time where street lights are on, and periods where the are off - can I model that meaningfully?

As an example (not using count data, but just gaussian data that are divided in two groups), here's a time series that's cyclic and irregular:
![Screenshot 2024-06-21 at 16 04 59](https://github.com/nicholasjclark/mvgam/assets/25629697/bfc4dda6-3306-44c1-ab90-4a324b916907)

Let's say that there are two "conditions" (here "group"), that could be the binary environmental variable, such as artificial light being on or off.
<img width="1231" alt="Screenshot 2024-06-21 at 16 09 59" src="https://github.com/nicholasjclark/mvgam/assets/25629697/bba757af-004d-46f9-b413-e1223cc6cd89">

I've tried to model it with:
```r
mvgam1 <- mvgam(value ~ 
                  s(time, k = 16) +
                  group, # or without group
                data = df,
                family = gaussian(),
                backend = "cmdstanr")
```
But the effects seem strange, particularly for "a" (red), where the raw values are just linear with some noise:
<img width="1427" alt="Screenshot 2024-06-21 at 16 38 33" src="https://github.com/nicholasjclark/mvgam/assets/25629697/81f8c51f-cabe-42ba-a4db-eca6c11c77eb">

Here's a reprex (although `plot_mvgam_series()` seems to crash `reprex::reprex()`, so almost):
```r 
library(mvgam)
library(marginaleffects)
library(dplyr)
# See distributions in image below
t <- seq(from = 0, to = 20, length.out = 1000)
v1 <- rep(1, 500)
v2 <- rep(2, 500)
noise <- rnorm(1000, mean = 0.5, sd = 1)
values <- c(v1,v2) + noise
a <- rep("a", 500)
b <- rep("b", 500)
df <- data.frame(
  time = t,
  value = values,
  group = c(a,b)
) |> 
  mutate(value = if_else(time > 15, value - ((time-14)^1.2), value))
df <- bind_rows(df, df, df, df, df) |> 
  mutate(time = row_number(),
         season = as.integer(time / 1000),
         series = factor("A"))

plot_mvgam_series(data = df, y = "value", series = "all")
mvgam1 <- mvgam(value ~
                  s(time, k = 16) +
                  group,
                data = df,
                family = gaussian(),
                backend = "cmdstanr")

marginaleffects::plot_predictions(mvgam1, by = c("time", "group"), points = 0.2)
plot(mvgam1, type = "forecast")
```

Hope it makes sense! Watched the talk that's on Youtube, and am really impressed by the package and hoping I can leverage it in some more complex animal behaviour settings! :-)

**Comment by roaldarbol** [comment]
As an aside, would there be any way of knowing whether such a discrete event would have a delayed effect? Say, lights turn on and off for a 5 minute period, but the effect of that event plays out over the following 1 hour, despite the light no longer being on.

**Comment by nicholasjclark** [comment]
Hi @roaldarbol, thanks for the question and the interesting example. For this kind of problem, I'd probably ignore the smooth of `time` and just focus on the different structural changes that are happening. I've found a lot of use for including predictors that represent the time since some event happened. In this case, including a measure of the time since entering the "b" group can be an effective way to investigate the delayed effect of the "b" condition. Of course if there are consistent temporal dynamics that you'd need to deal with, you could include those as well. But I've left them out here to keep the point simple:

**Comment by roaldarbol** [comment]
Thanks for the reply! That makes a lot of sense, and I think it's a nice way to think about it. 
One of questions that are at the crux of this analysis is actually exactly whether the effect of the light is the *presence* or the *onset* of the light that has an effect (or possibly a mixture of the two). How would you go about that? I guess I could include both make three models, one with with a time-since-onset variable (like the one you fitted), one with a discrete effect (which I'm then not quite sure how I would fit) and one with both of them - and then compare them?

**Comment by nicholasjclark** [comment]
Sorry for the late reply. Yes I think that strategy sounds useful. The discrete effect would just be the same model but without the time since onset effect, so should be fairly simple
