### ISSUE TITLE
minor typos in stability functions

### ISSUE THREAD

**Issue by mdscheuerell** [nicholasjclark/mvgam#76]
Nice addition of the stability metrics!

FYI, it looks like you switched the language for the `prop_int_offdiag()` and `prop_int_diag()` functions [here](https://github.com/nicholasjclark/mvgam/blob/cbf7d005f077237d6035180f3d7acc3cc4a9aa56/man/stability.mvgam.Rd#L48) and [here](https://github.com/nicholasjclark/mvgam/blob/cbf7d005f077237d6035180f3d7acc3cc4a9aa56/man/stability.mvgam.Rd#L55) in that the former should be for *inter*- and the latter for *intra-species* interactions.

**Comment by nicholasjclark** [comment]
Great thanks for pointing those typos out @mdscheuerell. I've updated the [docs](https://nicholasjclark.github.io/mvgam/reference/stability.mvgam.html) now to give more accurate descriptions. I really appreciate all the help getting these thoughts together
